# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-29 21:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pandas', '0002_tutorial_playlista'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorial',
            name='planowana_liczba_odcinkow',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
