# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-30 10:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pandas', '0003_tutorial_planowana_liczba_odcinkow'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item_Karuzeli',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tytul', models.CharField(max_length=30)),
                ('krotki_opis', models.CharField(max_length=125)),
                ('zdjecie', models.FileField(upload_to=b'')),
                ('tutorial_link', models.CharField(blank=True, max_length=125, null=True)),
                ('webpage_link', models.CharField(blank=True, max_length=125, null=True)),
                ('aktywny', models.BooleanField(unique=True)),
            ],
        ),
    ]
