# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-30 11:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pandas', '0004_item_karuzeli'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item_karuzeli',
            name='aktywny',
            field=models.CharField(max_length=25, unique=True),
        ),
    ]
