# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-10 20:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pandas', '0007_auto_20170610_2208'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item_karuzeli',
            old_name='aktywny',
            new_name='active',
        ),
        migrations.RenameField(
            model_name='item_karuzeli',
            old_name='krotki_opis',
            new_name='describtion',
        ),
        migrations.RenameField(
            model_name='item_karuzeli',
            old_name='zdjecie',
            new_name='picture',
        ),
        migrations.RenameField(
            model_name='item_karuzeli',
            old_name='tytul',
            new_name='title',
        ),
    ]
